<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="AddressServiceTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-05-26T16:19:34" hostname="LAPTOP-Q9T3UUC8" time="0.735">
  <properties/>
  <testcase name="givenMultipleContact_WhenAdded_ShouldSyncWithDB()" classname="AddressServiceTest" time="0.735"/>
  <system-out><![CDATA[Contact Being Added:Palak
Contact Being Added:Paras
Contact Added:Paras
Contact Added:Palak
]]></system-out>
  <system-err><![CDATA[java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Parass@gmail.com' for key 'addressbook.PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1333)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2111)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1338)
	at AddressBookConnection.addNewContact(AddressBookConnection.java:126)
	at AddressBookConnection.lambda$addMultipleContactsToDBUsingThread$0(AddressBookConnection.java:146)
	at java.base/java.lang.Thread.run(Thread.java:834)
AddressBookException
	at AddressBookConnection.addNewContact(AddressBookConnection.java:135)
	at AddressBookConnection.lambda$addMultipleContactsToDBUsingThread$0(AddressBookConnection.java:146)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'Pss@gmail.com' for key 'addressbook.PRIMARY'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1333)
	at com.mysql.cj.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2111)
	at com.mysql.cj.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1338)
	at AddressBookConnection.addNewContact(AddressBookConnection.java:126)
	at AddressBookConnection.lambda$addMultipleContactsToDBUsingThread$0(AddressBookConnection.java:146)
	at java.base/java.lang.Thread.run(Thread.java:834)
AddressBookException
	at AddressBookConnection.addNewContact(AddressBookConnection.java:135)
	at AddressBookConnection.lambda$addMultipleContactsToDBUsingThread$0(AddressBookConnection.java:146)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]></system-err>
</testsuite>
